name: Delete Files Every 6 Minutes

on:
  schedule:
    - cron: '*/6 * * * *'  # รันทุก 6 นาที

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
        
      - name: Delete all files in img folder
        run: |
          rm -rf ./img/*  # ลบไฟล์ทั้งหมดในโฟลเดอร์ img

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Deleted files in img folder" || echo "No changes to commit"
          git push
